webrpc/webrpc

- schema/ridl/example1.ridl
- schema/ridl/lexer.go
- schema/ridl/parser.go
- schema/ridl/ridl.go
- schema/ridl/ridl_test.go
- schema/ridl/state.go
- schema/schema.go
- schema/schema_test.go
- schema/service.go
- schema/var_type.go
```
go test -v github.com/webrpc/webrpc/schema/ridl
```
> WIP: ridl lexer & parser

- schema/ridl/parser.go
- schema/ridl/ridl_test.go
Hey @pkieltyka, what do you think of this one? should fix #51 
Closes https://github.com/webrpc/webrpc/issues/51
> Fix extra whitespace in RIDL definition

- schema/message.go
- schema/var_type.go
This allows external tools like https://github.com/golang-cz/go2webrpc to build full webrpc schema.
> Export schema.VarType expression

- _examples/golang-basics/example.gen.go
The latest github.com/webrpc/gen-golang@v0.7.4 now fixes #74, #104 and #105.
See
https://github.com/webrpc/gen-golang/releases/tag/v0.7.4
https://github.com/webrpc/gen-golang/commit/7e1449e9a4b67dc9a8cdd5602c2dcd7215445d82
> Fix methods with no response value

- _examples/golang-nodejs/client/client.gen.mjs
- _examples/hello-webrpc-ts/webapp/src/client.gen.ts
- _examples/hello-webrpc/webapp/client.gen.js
- _examples/node-ts/webapp/client.gen.ts
https://github.com/webrpc/gen-typescript/pull/1
https://github.com/webrpc/gen-javascript/pull/1
Update examples with the new typescript/javascript generators.
> Apply the fetch wrapper fixes from typescript/javascript generators

- .github/workflows/release.yml
- .goreleaser.yml
- Makefile
Build webrpc-gen binary for multiple OS/archs.
Create a Github release with changelog & attach the binaries.
> CI: Run Goreleaser on new git tag

- Makefile
https://github.com/webrpc/webrpc/issues/132
> Improve testing suite

- cmd/webrpc-test/main.go
- tests/schema.go
- Allow test binary to print out ridl scheme
> Allow webrpc-test binary to print out ridl scheme

- schema/error.go
- schema/ridl/ridl.go
- schema/ridl/ridl_test.go
- Default error HTTP status code should be 400
- Add RIDL tests for custom errors
> Fix default error HTTP status code, add more RIDL tests

- _examples/hello-webrpc-ts/webapp/src/client.gen.ts
- _examples/node-ts/webapp/client.gen.ts
> Regenerate examples (latest TypeScript example)

- cmd/webrpc-gen/main.go
- gen/gen.go
A life saver for template generator authors.
How did I live without this? Well, I was always logging the schema (or template vars) by hand in webrpc-gen binary or in the templates by `printf "%+v" .`. This is gonna make things so much easier.
```
$ webrpc-gen -schema=./schema/test.ridl -target=debug -some=other -options
(struct { *schema.WebRPCSchema; SchemaHash string; WebrpcGenVersion string; WebrpcGenCommand string; WebrpcTarget string; WebrpcErrors []*schema.Error; Opts map[string]interface {} }) {
WebRPCSchema: (*schema.WebRPCSchema)(0x140002c8000)({
WebrpcVersion: (string) (len=2) "v1",
SchemaName: (string) (len=4) "Test",
SchemaVersion: (string) (len=7) "v0.10.0",
Types: ([]*schema.Type) (len=4 cap=4) {
(*schema.Type)(0x140002cc000)({
Kind: (string) (len=4) "enum",
Name: (string) …
```
> Add -target=debug to print schema object incl. Go type information

- _examples/golang-basics/example.gen.go
- _examples/golang-imports/api.gen.go
- _examples/golang-nodejs/go.sum
- _examples/golang-nodejs/server/server.gen.go
- _examples/hello-webrpc-ts/server/hello_api.gen.go
- _examples/hello-webrpc/server/hello_api.gen.go
- tests/client/client.gen.go
- tests/server/server.gen.go
See https://github.com/webrpc/gen-golang/pull/29
> Update to golang@v0.12.5: Simplify Enums to TextMarshalers

- _examples/golang-basics/example.gen.go
- _examples/golang-imports/api.gen.go
- _examples/golang-nodejs/server/server.gen.go
- _examples/hello-webrpc-ts/server/hello_api.gen.go
- _examples/hello-webrpc/server/hello_api.gen.go
- tests/client/client.gen.go
- tests/server/server.gen.go
- https://github.com/webrpc/gen-golang/pull/31
- https://github.com/webrpc/gen-golang/pull/36
- https://github.com/webrpc/gen-golang/pull/35
- https://github.com/webrpc/gen-golang/pull/34
- https://github.com/webrpc/gen-golang/pull/33
- https://github.com/webrpc/gen-golang/pull/32
- https://github.com/webrpc/gen-golang/pull/37
> Update to golang@v0.13.1

- _examples/golang-basics/example.gen.go
- _examples/golang-nodejs/server/server.gen.go
- _examples/hello-webrpc-ts/server/hello_api.gen.go
- _examples/hello-webrpc-ts/webapp/src/client.gen.ts
- _examples/hello-webrpc/server/hello_api.gen.go
- _examples/node-ts/webapp/client.gen.ts
- gen/errors.go
- tests/client/client.gen.go
- tests/schema/test.debug.gen.txt
- tests/server/server.gen.go
In order to support https://github.com/webrpc/webrpc/pull/237
> Define new webrpc errors

- gen/template_source.go
See: https://github.com/webrpc/webrpc/issues/211
> do not create cache directory if there is 0 templates

- README.md
https://github.com/webrpc/gen-kotlin
Kudos to @vodamiro and [MeguMethod](https://www.megumethod.com).
> Add Kotlin client generator

- _examples/golang-basics/example.gen.go
- _examples/golang-imports/api.gen.go
- _examples/golang-nodejs/server/server.gen.go
- _examples/hello-webrpc-ts/server/hello_api.gen.go
- _examples/hello-webrpc/server/hello_api.gen.go
- tests/client/client.gen.go
- tests/server/server.gen.go
- version.go
Without --tags option, git describe returns only annotated tags..
> Fix version: git describe --tags

- Makefile
- _examples/golang-basics/example.gen.go
- _examples/golang-nodejs/server/server.gen.go
- _examples/golang-sse/proto/chat.gen.go
- _examples/hello-webrpc-ts/server/hello_api.gen.go
- _examples/hello-webrpc/server/hello_api.gen.go
- go.mod
- go.sum
- tests/client/client.gen.go
- tests/server/server.gen.go
https://github.com/webrpc/gen-golang/pull/65
> Update to golang@v0.14.7 and all other dependencies (Go 1.19 compatible)

- README.md
- gen/embed.go
- go.mod
- go.sum
https://github.com/webrpc/gen-dart/releases/tag/v0.1.1
Kudos to @austinmilt for implementing https://github.com/webrpc/gen-dart/pull/3.
> Embbed dart client into webrpc-gen

- .github/.goreleaser.yml
https://goreleaser.com/customization/changelog/
> Goreleaser: Try to fix changelog with github-native impl

- .github/.goreleaser.yml
- .github/workflows/release.yml
https://goreleaser.com/deprecations/#brewstap
> Update to goreleaser/goreleaser-action@v6 with v2 yaml

- gen/gen.go
- tests/schema/test.debug.gen.txt
Cross ref. https://github.com/webrpc/gen-golang/pull/72
> Add template version and template target to template vars

- _examples/golang-sse/webapp/src/rpc.gen.ts
- _examples/hello-webrpc-ts/webapp/src/client.gen.ts
- _examples/node-ts/server/server.gen.ts
- _examples/node-ts/webapp/client.gen.ts
- go.mod
- go.sum
https://github.com/webrpc/gen-typescript/releases/tag/v0.16.2
> Update to gen-typescript@v0.16.2

- _examples/golang-basics/README.md
- _examples/golang-basics/admin/admin.gen.go
- _examples/golang-basics/example.gen.go
- _examples/golang-basics/internal/internal.gen.go
- _examples/golang-nodejs/server/server.gen.go
- _examples/golang-sse/proto/chat.gen.go
- _examples/hello-webrpc-ts/server/hello_api.gen.go
- _examples/hello-webrpc/server/hello_api.gen.go
- go.mod
- go.sum
- tests/client/client.gen.go
- tests/server/server.gen.go
https://github.com/webrpc/gen-golang/pull/84
> Update to gen-golang@v0.18.1: Opinionated Sonic config

- _examples/golang-basics/admin/admin.gen.go
- _examples/golang-basics/example.gen.go
- _examples/golang-basics/internal/internal.gen.go
- _examples/golang-nodejs/server/server.gen.go
- _examples/golang-sse/proto/chat.gen.go
- _examples/hello-webrpc-ts/server/hello_api.gen.go
- _examples/hello-webrpc/server/hello_api.gen.go
- go.mod
- go.sum
- tests/client/client.gen.go
- tests/server/server.gen.go
https://github.com/webrpc/gen-golang/releases/tag/v0.18.2
> Update to gen-golang@v0.18.2

- _examples/golang-basics/admin/admin.gen.go
- _examples/golang-basics/example.gen.go
- _examples/golang-basics/internal/internal.gen.go
- _examples/golang-nodejs/server/server.gen.go
- _examples/golang-sse/proto/chat.gen.go
- _examples/hello-webrpc-ts/server/hello_api.gen.go
- _examples/hello-webrpc/server/hello_api.gen.go
- go.mod
- go.sum
- tests/client/client.gen.go
- tests/server/server.gen.go
https://github.com/webrpc/gen-golang/releases/tag/v0.18.4
```
webrpc-gen -target=golang -json=sonic
```
> Update to gen-golang@v0.18.4 to improves Sonic JSON encoding performance

- builder
> Remove a file that was committed by mistake
