- schema/ridl/parser.go
- schema/ridl/ridl_test.go
> I think tab could work to delimit, but that is pretty much it, as some people might want space or other characters in their value, prob not tab or newline tho
@pkieltyka accepting spaces and handling cases like:
```
+ tag = this a tag value with # spaces # and hash# sign # and this is a comment
```
would be problematic from the parser's point of view (because identifying a comment would depend on the context and we'll have to ask things like _is this the last `#` preceded by `[whitespace]` on this line?_)
What we can do to solve this problem is to look for [whitespace] or [newline] to mark the end of a token, and also add support for quoted values that may include [whitespace]. See below:
```
+ json = field_2 # a comment
+ go.tag.db = field_2 # a comment
+ go.tag.db.1 = …
```
> Extend delimiters for tag values

- _examples/golang-basics/Makefile
- gen/gen.go
- gen/template_source.go
- go.mod
- schema/message.go
- schema/schema.go
- schema/service.go
- schema/var_type.go
- webrpc.go
* support to search `github.com/webrpc/gen-XXX` for target template source if `-target=NAME` is used, where XXX will be swapped for NAME
* automatically cache downloaded templates from git sources in `${os.TempDir()}/webrpc-cache/${hash}-${genName}` -- the cache will be refreshed automatically each hour, it also is aware of versions in the target path, so it will keep those separate, and it also supports target option to refresh cache if you ask it to
* remove use of github.com/pkg/errors and use just stdlib instead
> minor updates + git fetch cache support

- webrpc.go
Remove unused top-level `VERSION` variable. I removed it in #119, but I think it reappeared after I did `git rebase -X theirs master`.
The `VERSION` var was moved over to webrpc-gen https://github.com/webrpc/webrpc/blob/master/gen/version.go#L6 and is passed to the generators as a `{{.WebrpcGenVersion}}` template variable.
> Remove obsolete webrpc version variable

- schema/data_type.go
I'm not sure if we have any plans for `T_Primitive`, but it's currently unused. All the [basic types](https://github.com/webrpc/webrpc/tree/master/schema#basic-types) has their own kind.
> Schema: Remove unused kind T_Primitive

- .github/workflows/release.yml
- .goreleaser.yml
Each new `git tag` will release a new version of `webrpc-gen` as a Homebrew tap to https://github.com/webrpc/homebrew-tap repository.
```
brew install webrpc/tap/webrpc-gen
```
> Publish webrpc-gen as a Homebrew tap automatically

- gen/README.md
- gen/funcmap.go
- gen/funcmap_array.go
- gen/funcmap_flow.go
- gen/funcmap_generic.go
- gen/funcmap_string.go
- gen/funcmap_test.go
Arrays are needed to fix custom struct tags in Golang generator, see https://github.com/webrpc/gen-golang/issues/9.
> webrpc-gen v0.8.0: Implement template arrays

- cmd/webrpc-gen/main.go
- gen/template_source.go
- Fixes #164
- Refresh cache only if we can fetch all files from remote git
- Fall-back to old (over TTL) cache on git fetch error
- Fetch *.go.tmpl files only (was *.tmpl)
- Pre-fetch all template files when FS is initially loaded
- Print new webrpc-gen cache summary
```
$ webrpc-gen -schema=./tests/schema/api.ridl -target=golang -pkg=client -client -out=./tests/client/client.gen.go
=======================================
|      webrpc generated summary       |
=======================================
webrpc-gen version : v0.8.x-dev
target             : github.com/webrpc/gen-golang
target cache       : /var/folders/23/vc4gzw8n52gc17yx4wfqfj3c0000gn/T/webrpc-cache/2568534563-gen-golang
target cache age   : 1h51m3s (failed to refresh: get git repository: GET …
```
> Relax template cache invalidation

- .github/workflows/cache.yml
Github cache eviction policy:
- GitHub will remove any cache entries that have not been accessed in over 7 days.
> Invalidate Github Actions cache every day

- gen/funcmap_string.go
- schema/ridl/ridl.go
- schema/service.go
- schema/type.go
- schema/var_name.go
Remove unnecessary schema.VarName type
It was difficult to work with schema.VarName (custom string type) in Go templates.
Calling `{{ $type.Name }}` failed with the following error:
```
command failed: template: struct.go.tmpl:9:17: executing "struct" at <.Name>: wrong type for value; expected string; got schema.VarName
```
This change will remove type-casting via `{{ printf "%v" $typeName }}` from templates and improve readability.
> Remove unnecessary schema.VarName type

- schema/ridl/error_parser.go
- schema/ridl/parser.go
- schema/ridl/parser_test.go
- schema/ridl/syntax_error_test.go
```diff
- error <code> <name> <message> [-- <status code>]
+ error <code> <name> <message> [HTTP <status code>]
```
- Improve error parser error messages.
- Add more error parser tests.
- Add invalid error parser tests.
> Update the RIDL error syntax & parser

- gen/README.md
- gen/errors.go
- gen/gen.go
- schema/error.go
- tests/client/client.gen.go
- tests/client/client.go
- tests/server/server.gen.go
Pass built-in errors to generators, so we don't need to maintain the list of core webrpc errors in individual templates.
> Add built-in webrpc errors

- schema/error.go
If someone defined HTTP 200 for a schema error, the webrpc clients wouldn't recognize it as an error. Instead, they'd treat the response body as a regular response data object.
> Schema errors: HTTP status code must be between 400-599

- cmd/webrpc-test/main.go
- tests/client/client.go
- tests/embed.go
- tests/server/server.go
Will remove the need for waiting for the test server readiness via custom scripts, ie.
https://github.com/webrpc/gen-typescript/blob/a80789817830a8e55480745111eb259da5eeedf6/tests/test.sh#L13-L14
> Implement `webrpc-test -waitForServer -timeout=10s'

- cmd/webrpc-gen/main.go
- gen/gen.go
Works well with the -out= flag, same as other targets. Removes the need for the special -test flag.
Bump version to v0.13.x-dev
> webrpc-gen: Add -target=json CLI flag

- gen/funcmap.go
- go.mod
1. Useful for debugging template vars as comments in the generated code:
```
/* {{- dump .TemplateVar -}} */
```
2. Useful for debugging template vars in webrpc-gen stderr output:
```
{{- stderrPrintf (dump .) -}}
{{- exit 1 -}}
```
> Implement dump template function

- cmd/webrpc-gen/main.go
- gen/funcmap_test.go
- gen/gen.go
- gen/helpers.go
This is very useful when developing/debugging templates that render invalid code.
> Generate code to the output file even on formatting error

- gen/gen.go
- tests/interoperability_test.go
- tests/schema/test.debug.gen.txt
This will help us track changes in the data object, which we pass down to the template generators.
> Make -target=debug output idempotent, track tests schema

- schema/ridl/ridl.go
- schema/ridl/type_parser.go
Error out on invalid RIDL:
```
service Chat
- SubscribeMessages() => (messages: stream Message)
```
should be
```diff
service Chat
- SendMessage(authorName: string, text: string)
-  - SubscribeMessages() => (messages: stream Message)
+  - SubscribeMessages() => stream (messages: Message)
```
> RIDL parser: Error out if stream is defined per argument type

- _examples/golang-basics/example_test.go
- schema/ridl/_example/example1-golden.json
- schema/ridl/parser.go
- schema/ridl/parser_test.go
- schema/ridl/ridl.go
- schema/type.go
- schema/var_type.go
- tests/schema/test.debug.gen.txt
- fix referencing enums in tests
- parse multiline comments 2 lines and more
- skip reading comments once we already hit one comment
> parse multiline comments 2 lines and more

- schema/ridl/_example/comments.ridl
- schema/ridl/lexer.go
- schema/ridl/parser.go
- schema/ridl/parser_test.go
- schema/ridl/tokenizer.go
some comments may not want to be published in the .gen output.
I've begun support where if a comment is written as `#! etc etc` the bang after the `#` will denote the line / entry as an internal comment and will not be included in the comments list, it will just be skipped. I've added a test case which should pass once the parser is updated.
also, the parser implementation for comments looks a bit weird, I think we'd be better off writing it like all other parsers, but as long as you can make it work, im not too fussy about it
> internal comments

- schema/ridl/_example/example1-golden.json
- schema/ridl/parser_test.go
- schema/ridl/tokenizer.go
- check if previous character is whitespace while parsing comments. if charachter is not whitespace we append current comment token to previous
> fix parsing comments with http scheme and fqdn

- gen/README.md
- schema/README.md
Declares the timestamp format to be ECMA Standard's ISO 8601 format. 
closes #278
> declare the timestamp standard

- .github/workflows/release.yml
https://goreleaser.com/deprecations/#-rm-dist
```
--rm-dist has been deprecated in favor of --clean.
```
This will fix the GoReleaser pipeline in master.
> Fix GoReleaser

- go.sum
- schema/ridl/parser.go
- schema/ridl/parser_node.go
- schema/ridl/parser_test.go
- schema/ridl/service_parser.go
- Keep parsing intact ( do not parse previous blocks ) and parse annotation and keep them in buffer. 
- Once I start parsing method definition I can assign current state of annotation buffer to this method.
> annotation parser improvements

- _examples/golang-basics/admin/admin.gen.go
- _examples/golang-basics/example.gen.go
- _examples/golang-basics/internal/internal.gen.go
- _examples/golang-nodejs/server/server.gen.go
- _examples/golang-sse/proto/chat.gen.go
- _examples/hello-webrpc-ts/server/hello_api.gen.go
- _examples/hello-webrpc/server/hello_api.gen.go
- go.mod
- go.sum
- tests/client/client.gen.go
- tests/server/server.gen.go
Support drop-in replacemanet JSON encoding packages, e.g.
`webrpc-gen -target=golang -json=github.com/bytedance/sonic`
> Update to gen-golang@v0.18.0: Support alternative JSON encodings

- go.mod
- go.sum
- Adds support for `@deprecated` annotation.
- Improves summary/description of OpenAPI endpoints.
See https://github.com/webrpc/gen-openapi/releases/tag/v0.16.1
> Update to gen-openapi@v0.16.1

- go.mod
- go.sum
Groups service endpoints via OpenAPI tags
> Update to gen-openapi v0.16.2

- schema/ridl/internal/graph/graph.go
- schema/ridl/ridl.go
- schema/ridl/ridl_test.go
Right now it's impossible to import the same file twice, for instance `a -> b` + `b -> c` + `a -> c` causes a circular dependency.
This PR uses a circular graph analysis to avoid this issue, allowing for this kind of import while preventing cycles.
The current import test has been updated to import the same file twice with no cycle, another test case was added with cycle detection.
> Use a Graph to detect circular dependencies

- go.mod
- go.sum
https://github.com/webrpc/gen-openapi/releases/v0.16.3
* Escape quotes & improve endpoint summary/description by @VojtechVitek in https://github.com/webrpc/gen-openapi/pull/23
* Group service endpoints by OpenAPI tags by @VojtechVitek in https://github.com/webrpc/gen-openapi/pull/24
* generate operation id by @LukasJenicek in https://github.com/webrpc/gen-openapi/pull/25
**Full Changelog**: https://github.com/webrpc/gen-openapi/compare/v0.16.0...v0.16.3
> Update to openapi@v0.16.3
